Add Chaos Engineering and Testing ADR
operate-first/sre pull request #12
Opened 2022-05-01 20:38 UTC by chaitanyaenr

This commit adds an ADR which walks through:
- Current problem around possibility ofa system or service not designed and
  architected to handle failures leading to downtime in production environment.
- Proposed solutions to overcome the problem by publishing best practices,
  methodology and test framework to use to drive adoption of chaos testing.

2022-05-01 20:38 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **amfred** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @amfred` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fsre).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/sre/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["amfred"]} -->

2022-05-01 20:39 UTC, chaitanyaenr commented
@david-martin PTAL. Thanks.

2022-05-03 08:33 UTC, david-martin commented on ADRs/RH/SIG-SRE/ADR-00002-Chaos-Testing-and-Engineering.md
> +The network is homogeneous.
```suggestion
* The network is reliable.
* There is consistent resource usage with no spikes.
* There is zero latency.
* Bandwidth is infinite.
* The network is secure.
* Topology never changes.
* The network is homogeneous.

```

2022-05-03 08:35 UTC, david-martin reviewed
1 suggestion, otherwise good to merge

2022-05-03 08:36 UTC, david-martin commented on ADRs/RH/SIG-SRE/ADR-00002-Chaos-Testing-and-Engineering.md
> +The network is homogeneous.
The preview showed this as a single paragraph, so converting to a list for easier reading and emphasis on the number of assumptions.

2022-05-03 18:57 UTC, chaitanyaenr commented
> 1 suggestion, otherwise good to merge

Fixed. Thanks!

2022-05-04 17:40 UTC, lisa requested changes, later dismissed
/hold

As mentioned in #7, there is an ADR numbering conflict between #7, #11 and #12 (this PR). Each of them seems to want to use ADR-00002. Do you want to work with the other authors to resolve the conflict?

2022-05-04 17:44 UTC, chaitanyaenr commented
@lisa @david-martin I will bump up the ADR number of this draft to ADR-00004, this way #7 and #11 can use ADR-00002 and ADR-00003. Thanks.

2022-05-04 17:45 UTC, lisa commented
@chaitanyaenr Lovely, thank you.

2022-05-04 17:46 UTC, lisa commented
/hold cancel

2022-05-04 17:46 UTC, chaitanyaenr commented
> @lisa @david-martin I will bump up the ADR number of this draft to ADR-00004, this way #7 and #11 can use ADR-00002 and ADR-00003. Thanks.

Done!

2022-05-05 14:55 UTC, david-martin commented
/lgtm
/approve

2022-05-05 14:55 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/sre/pull/12#issuecomment-1118656335" title="Approved">david-martin</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fsre).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/sre/blob/main/OWNERS)~~ [david-martin]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-05-05 14:57 UTC, merged